name = "MyfirstPackage"
uuid = "aff8e29a-8c77-4133-bcd7-d8a05881e8b5"
authors = ["qianhou"]
version = "1.0.0-DEV"

[deps]
OMEinsum = "ebe7aa44-baf0-506c-a96f-8464559b3922"

[compat]
julia = "1.10"
OMEinsum = "0.8"  

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
